### ISSUE TITLE
mmdetection v1.2 won't install without a GPU

### ISSUE THREAD

**Issue by sekh77** [DevashishPrasad/CascadeTabNet#10]
Hi - It looks like I can't install mmdetection v1.2 without a GPU even though I installed CUDA10.0 and the appropriate version of cuDNN. Is this understanding correct? Clearly my installtion is failing with the error - "no CUDA-capable device is detected". 

I'm unable to find any proper information in open-mmlabs about this subject. However, I'm able to install v2.0 without GPU because I believe 2.0 has a default check to fallback to CPU if a GPU device is not found.

Keeping your model at v1.2 for people who run their projects with no GPU will likely make the usage  of these models limited. Is there a way to convert the model trained on v1.2 to v2.0?

Thanks,
Sekhar H.

**Comment by AyanGadpal** [comment]
Hey @sekh77 ,
You have made a good point. We are open for pull request and contribution on this issue.
You can try [this](https://github.com/open-mmlab/mmdetection/blob/master/tools/upgrade_model_version.py) script to convert our model weight to mmdetection 2.0, however i am not sure how that will work
Also the pre trained weights of [Cascade Mask R-CNN HRNetV2p-W32](https://github.com/open-mmlab/mmdetection/tree/master/configs/hrnet) are not yet available in mmdetection 2.0 for us to train it.
Thanks you

**Comment by StanleyGan** [comment]
@AyanGadpal it seems the pre trained weights are available in the latest version of mmdetection: https://github.com/open-mmlab/mmdetection/tree/master/configs/hrnet. I have tried using the script to convert your model weight to v2.0, but got an error `SyntaxError: There are syntax errors in config file /tmp/tmp_6xk79fb.py`, then `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxlpsyqsm/tmp_fchbnd8.py'`.

**Comment by sukumar-varma** [comment]
@StanleyGan Did you manage to solve this issue?

**Comment by StanleyGan** [comment]
@sukumar-varma I did it a while ago and don't remember vividly. Basically there were some syntax errors when the conversion script was trying to convert to the latest version. And if you look closely, the checkpoints shared by the CascadeTabNet folks have some extra code related to their directory at the top of the checkpoint (/content/drive/My Drive/chunk cascade_mask_rcnn_hrnetv2p_w32_20e.py). So, you will have to edit the checkpoint, remove the directory string. Then try to convert it again using the script. You will also have to use the new format of the config file as shared in my link. But do note that there is a drop in performance using the converted weights. Please let me know if you have other errors. I might not list down all the details.
