### ISSUE TITLE
Reproduce research paper result

### ISSUE THREAD

**Issue by Alsonkong** [DevashishPrasad/CascadeTabNet#105]
Hi, I am trying to reproduce the experiments and evaluation and wish to achieve the number stated in the paper. Would you guide me or simply write a readme file to explain how to conduct the experiments. Thanks

**Comment by Scheriaa** [comment]
Hello, I see that you have closed the issue. Did you manage to reproduce the results? In fact I am trying to fine tune the model on my own dataset. To do so,  I am  starting by trying to reproduce the results. Would you please share the script that you used for that? 
Thank you
