### ISSUE TITLE
do you have the script that convert you pytorch model to onnx

### ISSUE THREAD

**Issue by phamquiluan** [DevashishPrasad/CascadeTabNet#107]
do you have the script that convert you pytorch model to onnx

**Comment by ManishDV** [comment]
No, We haven't worked on that. But you can refer to [this](https://github.com/pytorch/pytorch/blob/master/docs/source/onnx.rst) link for converting the pytorch model to onnx

**Comment by pbamotra** [comment]
@phamquiluan Hopefully, this helps - https://gist.github.com/pbamotra/f6216bcf2af9ddcfb4ab1c017c6fe2ab

**Comment by pbamotra** [comment]
@phamquiluan maybe this helps -- https://gist.github.com/pbamotra/d48b2940d84a214475dff9be6b5dab8c

**Comment by kbrajwani** [comment]
Hey @pbamotra can you tell me about inference script? i have converted onnx from your gist.

**Comment by pbamotra** [comment]
@kbrajwani  please refer to https://github.com/open-mmlab/mmdetection/blob/v2.10.0/tools/deployment/pytorch2onnx.py

**Comment by kbrajwani** [comment]
I have already converted pytorch to onnx. But don't know how to inference from it.

**Comment by pbamotra** [comment]
Check out the verification part in that script -- https://github.com/open-mmlab/mmdetection/blob/bec24ea4ff55767256ac873c4b2e856d3f1dba1e/tools/deployment/pytorch2onnx.py#L72 

Line 72 onwards where the authors compare the outputs of pytorch model and onnx model

**Comment by kbrajwani** [comment]
Thanks i will look into it.

**Comment by kbrajwani** [comment]
Hey i have converted model and testing it with api and threads. It's taking much memory at every inference time. Might be onnx model stores computation in cache. Has anyone encounter and solve the same problem?

**Comment by amar512-prog** [comment]
Hey guys, I am trying to use converted CascadTabNet onnx model in onnxruntime-web library on Node.js. But I'm getting some operations('Range') are missing. I am using opset 11 in pytorch2onnx but in onnxruntime that operation is present in opset 12. 
Can anyone help how to solve this?
In addition, since both are using same opset version why is it in different version?
Any other ideas how to use CascadTabNet pytorch model in javascript will be also appreciated.

**Comment by shubhasrao** [comment]
Hi @kbrajwani Just wondering if you were successful in converting the model to onnx and using it in inference mode. I have run into multiple issues. I see many warnings but no errors but I cannot visualise the generated model. Are you please able to share some script/links for conversion and inference? thanks!

**Comment by phamquiluan** [comment]
Bai!
