### ISSUE TITLE
Variation in Results

### ISSUE THREAD

**Issue by mdv3101** [DevashishPrasad/CascadeTabNet#12]
I was running the evaluation on ICDAR-13 using [pre-trained model](https://drive.google.com/open?id=1-mVr4UBicFk3mjUz5tsVPjQ4jzRtiT7V) which you have provided and using the default [configuration file](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Config/cascade_mask_rcnn_hrnetv2p_w32_20e.py).
There is a huge variation in the results.
`recall:1.0, precision:0.843, f_measure:0.9216`

Are you doing pre-processing on the testing images as well??

**Comment by DevashishPrasad** [comment]
What split did you use? 

We will soon release the train-test split that we used to evaluate the model.

**Comment by mdv3101** [comment]
In the paper you have mentioned that the evaluation is done on 238 images of ICDAR-13. I haven't train the model, I was just using the pre-trained weights which you have provided and run the evaluation on entire 238 images. Is there something I am missing? Are you using a sub-set of ICDAR-13 for evaluation?

**Comment by DevashishPrasad** [comment]
In paper we clearly mentioned that 238 images are split into train and test sets. So we used a subset of ICDAR-13 for evaluation.

There is a small error in the exact numbers we mentioned in the paper, so we will release the train set and evaluation set soon.

**Comment by DevashishPrasad** [comment]
We released the Train-test split that we used.

Please find the names of PDFs here : CascadeTabNet/Evaluations/Readme.md 

We used 48 images for training and 190 images for testing.

So please leave 48 images images while evaluating and perform the evaluation on the rest 190 images.

**Comment by mdv3101** [comment]
Hi @DevashishPrasad, Even after removing the 48 images from testing, i am unable to reproduce the results. Can you please check the [model file](https://drive.google.com/open?id=1-mVr4UBicFk3mjUz5tsVPjQ4jzRtiT7V)?

Also can you provide the dataset which you have used for training the General Model? It would be very helpful.

**Comment by AyanGadpal** [comment]
Hey @mdv3101,
1) Please check the revised Train/test split, as there was one pdf *missing* in the last update.
2) What threshold you have kept for confidence, in our case we have kept it **0.998**
3) Can you please send us your XML (according to ICDAR 13 format), Here is the link to [**ours XML**](https://drive.google.com/drive/folders/1ZZTQ4fIsGCqdonWFsoV0UEWpU8IC_FIF?usp=sharing) 
4) Also, please let us know which script you have used for evaluation. I would recommend using [**this**](https://github.com/DevashishPrasad/CascadeTabNet/tree/master/Evaluations) script to evaluate your results.
5) We will be releasing the General Dataset soon.
