### ISSUE TITLE
Use of detected cell bounding box for cell text extraction

### ISSUE THREAD

**Issue by Atul997** [DevashishPrasad/CascadeTabNet#128]
In processing of borderless tables detected cells are used in calculating rows and columns but not in the extraction of text in cells. Can you explain the reason ?

**Comment by Vibha111094** [comment]
I also had a similar question.
Are we supposed to further perform ocr on the cell?
Any advice on this will be very helpful

**Comment by AyanGadpal** [comment]
Hi @Atul997 and @Vibha111094,
Yes, 
We are providing you with the Text Coordinates and their position in Table. If you want the text, you will need to use OCR on the cells.
