### ISSUE TITLE
Explain the coordinates in Table Structure Recognition

### ISSUE THREAD

**Issue by ZafarShadman09** [DevashishPrasad/CascadeTabNet#135]
This really is an amazing work thank you.
But I am having trouble understanding the coordinates in the table structure recognition.
<Coords points="28,970 28,1299 1750,1299 1750,970"/>
I am unable to interpret which is x0,x1, y0,y1.

These value seem to be repeating 1299 1750.

**Comment by ZafarShadman09** [comment]
Got it.
<Coords points="28,970 28,1299 1750,1299 1750,970"/>

x,y is actually the point and its <space> separated and its all four corner coordinates

**Comment by MahimaBarot** [comment]
I am still unclear about this coordinate system. In what format are they returning the values? also in pixels or point?

**Comment by MahimaBarot** [comment]
> Got it.
> 
> x,y is actually the point and its separated and its all four corner coordinates

I am still unclear about this coordinate system. In what format are they returning the values? also in pixels or point?
