### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'nms'

### ISSUE THREAD

**Issue by dennis21bb** [DevashishPrasad/CascadeTabNet#138]
I'm getting the error while trying to run the code, at the following line: 

_result = inference_detector(model, i)_

did anyone run into the same issue and has a solution?

**Comment by mfl22** [comment]
Are you using `mmdetection` v1 or v2?
I ran into the same issue with mmdet v2, just copy the relevant attribute from `mmdet/configs/_base_/models/cascade_mask_rcnn_r50_fpn.py` (you will need to repeat that for several attributes).
The config file `cascade_mask_rcnn_hrnetv2p_w32_20e_v2.py` needs to be updated...

**Comment by dennis21bb** [comment]
> Are you using `mmdetection` v1 or v2?
> I ran into the same issue with mmdet v2, just copy the relevant attribute from `mmdet/configs/_base_/models/cascade_mask_rcnn_r50_fpn.py` (you will need to repeat that for several attributes).
> The config file `cascade_mask_rcnn_hrnetv2p_w32_20e_v2.py` needs to be updated...

Yeah that seems to be the problem then, can you tell me where exactly the attribute needs to be added?

**Comment by omrastogi** [comment]
hi @dennis21bb @mfproto, I've come across the same problem and am looking where to update the attribute. Can you please help me, with this. Thanks

**Comment by mfl22** [comment]
@omrastogi I created a pull request #144 so you can try that...
