### ISSUE TITLE
Empty XML files as output

### ISSUE THREAD

**Issue by Prakhar-97** [DevashishPrasad/CascadeTabNet#16]
I was trying to run the code but it is returning empty XML files.

**Input file**
![cTDaR_t10011](https://user-images.githubusercontent.com/42904569/82202385-74277400-991f-11ea-8fc3-57258b72a055.jpg)

**Output XML file**
[cTDaR_t10011.txt](https://github.com/DevashishPrasad/CascadeTabNet/files/4643489/cTDaR_t10011.txt)

**Comment by DevashishPrasad** [comment]
can you tell where did you get this image from? Is it from any of the datasets we have used?

**Comment by Prakhar-97** [comment]
Yes, I am using the image from ICDAR-2019 Track A test dataset

**Comment by kshitijkapadni** [comment]
Have you tried uncommenting the visualization snippets present is all the Table Structure Recognition files? If not, try that and visualize it and it will probably say where the problem begins. If you are unable to identify the problem share the results here so that we can help.

**Comment by Prakhar-97** [comment]
Was able to produce XML files, the issue was cv2_imshow(), it was breaking the loop, commenting all such lines helped to produce the output
How do you propose to have a visualization of all the input images.

I had also added from google.colab.patches import cv2_imshow

**Comment by kshitijkapadni** [comment]
from google.colab.patches import cv2_imshow
cv2_imshow(image)

We used this for visualization as colab doesn't support cv2.imshow.
