### ISSUE TITLE
Error: cannot connect to X server   

### ISSUE THREAD

**Issue by man0007** [DevashishPrasad/CascadeTabNet#18]

**Comment by DevashishPrasad** [comment]
If you are using Google Colaboratory (Colab), Then you need add

from google.colab.patches import cv2_imshow
and replace all the cv2.imshow with cv2_imshow

**Comment by man0007** [comment]
HI,

Thanks for the quick response, I'm running it in my local linix machine.

Thanks,
Anand.

**Comment by man0007** [comment]
Any solution, as i mentioned, i'm not running it in colab but still getting this error?

**Comment by sekh77** [comment]
Install an X Server and enable RDP in your Azure Linux VM. Follow this guide - 

> https://docs.microsoft.com/en-us/azure/virtual-machines/linux/use-remote-desktop.

After you enable RDP, you can use the Windows Remote Desktop Connection to connect to your Azure Linux VM. This will provide you with a full-fledged Desktop screen with all graphical screens. OpenCV cannot show images in a UI if the X server is not configured with proper permissions. Open a Terminal from the Desktop, and issue the following commands from your home folder:

_> chmod 777 .Xauthority
> chmod 777 .ICEauthority
> cp .Xauthority .ICEauthority /root_

Test if the X server is responding by issuing the command - "xclock". If a UI wondow comes up with the clock, then your X server is working. OpenCV can then show results in a UI window.

**Comment by man0007** [comment]
After getting the bw image I pressed enter to get the Intersection image, but i could not see any bounding box and the XML is having only 2 rows: https://prnt.sc/sj6k90

xml output:
========

<?xml version="1.0" encoding="UTF-8"?>
<document>
  <table>
    <Coords points="339,626 1125,914 1125,914 1125,626"/>
  </table>
  <table>
    <Coords points="338,222 1125,541 1125,541 1125,222"/>
  </table>
</document>

**Comment by kshitijkapadni** [comment]
can you share the table intersection image?
