### ISSUE TITLE
Getting this error in windows: https://prnt.sc/sjhfw7

### ISSUE THREAD

**Issue by man0007** [DevashishPrasad/CascadeTabNet#22]

**Comment by AyanGadpal** [comment]
I was unable to reproduce the error you are getting, 
Please take a look at demo notebook :  [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1lzjbBQsF4X2C2WZhxBJz0wFEQor7F-fv?usp=sharing)
Do tell us if you are still getting that error or not
