### ISSUE TITLE
May i deploy to mobile device with tflite?

### ISSUE THREAD

**Issue by weinixuehao** [DevashishPrasad/CascadeTabNet#24]
How to deploy to mobile device if it is possible to deploy mobile device with tflite?

**Comment by DevashishPrasad** [comment]
The models are developed in Pytorch and TFlite needs tensorflow models, you willl need to convert models into tensorflow (using onnx may be) or else train the models in tensorflow itself.

**Comment by weinixuehao** [comment]
How is the inference speed that deploying to mobile using onnx? Do I need consider the cuda issue?

**Comment by DevashishPrasad** [comment]
Hi,

We did not test our models for any mobile deployment and cannot comment anything on it

**Comment by weinixuehao** [comment]
@DevashishPrasad Thanks a lot!
