### ISSUE TITLE
Is there any training model available to train the model to improve accuracy?

### ISSUE THREAD

**Issue by man0007** [DevashishPrasad/CascadeTabNet#27]
I could see that the model i not generalising well in the unseen data, so if there is any training model available it would be easy to improve model via training.

Please find the results for some sample tables with the respect to the 7 given models.
[results.zip](https://github.com/DevashishPrasad/CascadeTabNet/files/4655907/results.zip)

**Comment by DevashishPrasad** [comment]
If that is the case, you can finetune on any of the models we have provided.

and you can refer "https://www.dlology.com/blog/how-to-train-an-object-detection-model-with-mmdetection/" for finetuning mmdetection models

**Comment by man0007** [comment]
Is there any link to download the ICDAR Table data samples?

**Comment by DevashishPrasad** [comment]
Please refer supplementary material file (results.pdf)
