### ISSUE TITLE
not supporting cuda

### ISSUE THREAD

**Issue by weinixuehao** [DevashishPrasad/CascadeTabNet#29]
How to build mmdetection without cuda supporting?

**Comment by weinixuehao** [comment]
Install with CPU only
The code can be built for CPU only environment (where CUDA isn't available).

In CPU mode you can run the demo/webcam_demo.py for example. However some functionality is gone in this mode:

Deformable Convolution
Deformable ROI pooling
CARAFE: Content-Aware ReAssembly of FEatures
nms_cuda
sigmoid_focal_loss_cuda
So if you try to run inference with a model containing deformable convolution you will get an error. Note: We set use_torchvision=True on-the-fly in CPU mode for RoIPool and RoIAlign

CascadeTabNet is really need cuda?

**Comment by kshitijkapadni** [comment]
According to the documentation in the MMdetection v1.2 it requires GPU and CUDA and as we have used v1.2. Yes, it needs CUDA.
