### ISSUE TITLE
Predicted image co-ordinates are lifted uniformly above original cell value.

### ISSUE THREAD

**Issue by man0007** [DevashishPrasad/CascadeTabNet#31]
HI,

output xml coordinates plotted on the input images: 
https://prnt.sc/sl1f28
https://prnt.sc/sl1fi5
https://prnt.sc/sl1g42
(All blue lines are manually drawn based on the xml output coordinates for these images)

I have attached the input images which i have used for this model and i have drawn the bounding boxes manually using the XML output.

In all these images the bounding boxes are uniformly lifted upwards. By this I could sense that the image size that I'm sending is altered at the time of prediction and the xml output is having the co-ordinates of the altered image. (please correct me if this is not the case)

If above is true please let me know on where can i get the altered images, so that the xml output co-ordinates would match while plotted.

--------------------------------------------

The next question is, if the above is true, how the table detection coordinates  are matching correctly, for all 3 table images attached, apart from cell level, I have also drawn the bounding box for the entire table which fits perfectly. 

If all the cell level co-ordinates are realigned how come the table level co-ordinates are alone coming up correctly?

Thanks,
Anand.

**Comment by kshitijkapadni** [comment]
At first, we used to take only the ROI of the table for line detection and all the other post-processing and we used to pad the ROI with 10 px and while generating XML we subtracted the Padding amount.

I have updated the code, you can refer the latest code to generate XML.

**Comment by man0007** [comment]
Thanks for the quick responce!
