### ISSUE TITLE
Vertical Lines in Borderless Tables

### ISSUE THREAD

**Issue by Atul997** [DevashishPrasad/CascadeTabNet#32]
I ran model into my own dataset and results were like this for border less tables. Am I mis
sing something?

![res](https://user-images.githubusercontent.com/19590378/82634939-b05b1d00-9c1c-11ea-926a-5070f7ee2cd5.png)

**Comment by DevashishPrasad** [comment]
Can you show the original image?

**Comment by Atul997** [comment]
I can't post the whole image as they are confidential. Can you tell what is the issue or what changes I have to make?

**Comment by Atul997** [comment]
Can you suggest me which part I have to look at  exactly after model prediction in post processing of files?

**Comment by kshitijkapadni** [comment]
Hey Atul,

Actually the post-processing totally depends on the output of the cell masks produced by the model as you can observe in [main.py](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Table%20Structure%20Recognition/main.py) we pass cell masks along with table ROI for the borderless table. If the cell mask produced are not so accurate then this issue may occur. It is suggested that you fine-tune the model for better cell mask prediction.

**Comment by Atul997** [comment]
Okay. But I want to know how you guys generate annotation of data like which tool or any kind of custom scripts you have used?

**Comment by DevashishPrasad** [comment]
We used custom scripts to generate annotations. Sorry we do not intend to open source those scripts anytime soon. We are open for PRs

**Comment by Atul997** [comment]
I tested it on some public dataset but still that vertical lines problem is there. Some of them are
![pubtab](https://user-images.githubusercontent.com/19590378/83253286-5c2adc80-a1ca-11ea-9d45-ba2e6df3813a.png)
![pubto](https://user-images.githubusercontent.com/19590378/83253292-5e8d3680-a1ca-11ea-9c8b-32f0513778e0.png)
![putop](https://user-images.githubusercontent.com/19590378/83253293-5f25cd00-a1ca-11ea-8aa9-109957305213.png)

Can you please look and tell me what is wrong?
Here are the original images-
![PMC4196076_004_00](https://user-images.githubusercontent.com/19590378/83253448-9b592d80-a1ca-11ea-8ca5-8eec3224c156.png)
![PMC3765162_003_01](https://user-images.githubusercontent.com/19590378/83253706-0c004a00-a1cb-11ea-9d1f-56442ff70492.png)
![PMC5303243_003_00](https://user-images.githubusercontent.com/19590378/83253776-2f2af980-a1cb-11ea-9c24-587ad23c52eb.png)

**Comment by kshitijkapadni** [comment]
As I said the Post-processing totally depends on the output of the model for cell mask. The model is performing well on the ICDAR 19 because it was fine-tuned on ICDAR 19. Fine-tuning the model on your specific dataset will help you get better results.

**Comment by Atul997** [comment]
Okay. Thanks
