### ISSUE TITLE
Has an alternative for colab?

### ISSUE THREAD

**Issue by weinixuehao** [DevashishPrasad/CascadeTabNet#34]
I want to debug the code so that good understanding, I originally used vscode but gave up due to my mac did not support cuda so i tried to use colab which however debugging is not good experience to me and each operation is slow.

So have an alternative to replace colab or have you a some tips ?

**Comment by DevashishPrasad** [comment]
As per best of my knowledge you will need cuda to compile the MMdetection library because otherwise models won't load properly.

If you don't want to use colab then you will need a Cuda supported GPU  based local machine to run the code.

**Comment by AyanGadpal** [comment]
We have used colab in this Whole research.
As for speeding up the installation of mmdetection in colab, you can clone the mmdetection 1,2 repo in your drive and run installation from there. 
However this sometimes introduce cuda runtime error, which will require you to delete the mmdetection from drive and redo the whole process.

**Comment by weinixuehao** [comment]
@AyanGadpal @DevashishPrasad 
Thanks a lot!
