### ISSUE TITLE
Do i need cuda support in production

### ISSUE THREAD

**Issue by weinixuehao** [DevashishPrasad/CascadeTabNet#35]
How to deploy in production? My server is aliyun which has not gpu card.

**Comment by DevashishPrasad** [comment]
We are sure about how to deploy the models 

but as far as development is concerned you wil need cuda based GPU and cannot be done using a CPU

You will need to convert our GPU  based models to CPU using some third party libraries like ONNX

Again i am not sure about that it would work

**Comment by weinixuehao** [comment]
@DevashishPrasad 
Cloud gpu server cost is high so deploying on own computer come with a gpu card is better choice ?

**Comment by DevashishPrasad** [comment]
Yes I think so
