### ISSUE TITLE
Post-processing  in this test case is so slow

### ISSUE THREAD

**Issue by Gingersna** [DevashishPrasad/CascadeTabNet#36]
https://github.com/DevashishPrasad/CascadeTabNet/blob/7147b41edb6a7b75bfcb498921b2c7b678f391a6/Table%20Structure%20Recognition/main.py#L43-L53
test image:[https://raw.githubusercontent.com/cndplab-founder/ICDAR2019_cTDaR/master/test/TRACKB2/cTDaR_t10080.jpg]( cTDaR_t10080.jpg)

**Comment by kshitijkapadni** [comment]
Post-processing for borderless tables depends on the cell mask given by the model. If the model doesn't give accurate results we are trying to make it accurate in post-processing. This may be the case which is making it slow. 

Also, our research was focused on getting accuracy and we haven't focused on the time complexity.
