### ISSUE TITLE
checkpiont can not be loaded and dataset also

### ISSUE THREAD

**Issue by cqray1990** [DevashishPrasad/CascadeTabNet#38]
the dataset and checkpoint can not be loaded successful

**Comment by AyanGadpal** [comment]
Please elaborate the issue you are facing in more lucid, concise, and comprehensive manner.

**Comment by AyanGadpal** [comment]
1. For loading checkpoints, 
Please take a look at demo notebook :  [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1lzjbBQsF4X2C2WZhxBJz0wFEQor7F-fv?usp=sharing) 
2. For dataset, We will need more detail to resolve the issue

**Comment by cqray1990** [comment]
maybe it is my network result to fail load the dataset
