### ISSUE TITLE
Prediction in colab

### ISSUE THREAD

**Issue by Etisti** [DevashishPrasad/CascadeTabNet#39]
Hi, i'm a newbie with mmdetection, i had some issues (mentionned in the open issue's github too) trying to run it on cpu, so i decided to try a prediction in colab but i faced the error below and i could not find the solution alone

![image](https://user-images.githubusercontent.com/42436475/82933408-24355680-9f8a-11ea-92e1-075dcfde21f4.png)

**Comment by gireek** [comment]
Was anybody able to solve this issue?

**Comment by AyanGadpal** [comment]
I am unable to reproduce the error you are getting, 
Please take a look at demo notebook :  [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1lzjbBQsF4X2C2WZhxBJz0wFEQor7F-fv?usp=sharing)
Please tell us if this resolved your issue

**Comment by Etisti** [comment]
Thank you AyanGadpal, maybe it was a version problem since i used the last version of pytorch and mmdetection, your demo work very well thank you :)

**Comment by mtchibozo** [comment]
I believe it is a version error linked with the mmcv version. 
Try using the following line in the first cell of the colab notebook (instead of the default import of mmcv).
!pip install -q mmcv==0.4.3 terminaltables
