### ISSUE TITLE
cascade_mask_rcnn_hrnetv2p_w32_20e.py

### ISSUE THREAD

**Issue by cqray1990** [DevashishPrasad/CascadeTabNet#41]
when i read cascade_mask_rcnn_hrnetv2p_w32_20e.py i found numclass=81,why you set numclass=81,this is not correct?is it?

**Comment by DevashishPrasad** [comment]
At the time of inference it does not matter, and at the time of training : Please refer this blog https://www.dlology.com/blog/how-to-train-an-object-detection-model-with-mmdetection/

**Comment by cqray1990** [comment]
@DevashishPrasad But if so,is your model output classes is 81? the inference will be slow?

**Comment by DevashishPrasad** [comment]
81 classes were set by mistake, the training and testing went perfectly fine so didn't notice that issue. 

Also didn't test how it affects inference time.
