### ISSUE TITLE
Table structure recognition is not predicted for second table of demo image

### ISSUE THREAD

**Issue by nazarimilad** [DevashishPrasad/CascadeTabNet#44]
First and foremost, thanks for this interesting paper and also this repository!

Now, as you can see in the README, in the [demo gif](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/imgs/CVPR%20Teaser.gif) not only both tables are detected but structure recognition is successful for both tables (in the last step of the animation).  

However, when predicting this [demo image](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Demo/demo.png), I get the different results:

![image](https://user-images.githubusercontent.com/23218676/83686861-3e56e080-a5eb-11ea-9973-f03f1b355b87.png)

As you can see in the screenshot, both tables are detected succesfully. But in the right table no cell is recognised. In the left table, cells in the last columns are also not recognised. I'm using the same checkpoint file and configuration as in the [demo Jupyter notebook](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Demo/Cascade_TabNet_Demo.ipynb). I tried lowering the threshold, but that didn't help.

How can I improve the prediction so that I get the same performance as shown in the [demo gif](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/imgs/CVPR%20Teaser.gif)? Am I missing some postprocessing, or am I not using the optimal configuration, or something else? I'm not sure, I hope you could help.

Thanks!

**Comment by DevashishPrasad** [comment]
Hello @nazarimilad 

This is the perfect output from the model. After this you need to do the post-processing. For details about the postprocessing please refer the paper and find the code for the same in this repo.

Thanks
