### ISSUE TITLE
 the function of "Table Structure Recognition" folder

### ISSUE THREAD

**Issue by babyMonkey8** [DevashishPrasad/CascadeTabNet#45]
Hello, I have a question about the function of "Table Structure Recognition" folder. The "main" file under this folder can generate XML, so the generated XML file is used as the tag data of the model（training the model from scratch）?  Or generate XML files about the table structure based on the data predicted by the model?

**Comment by DevashishPrasad** [comment]
It is used to generate XML files about the table structure based on the data predicted by the model.

**Comment by babyMonkey8** [comment]
Thank you for your answer. In addition, because the size of my own image data is very large, I have another question: the pre training model (epoch_ 36. pth) what size of picture is suitable for prediction?

If I train my own data from scratch, do I need to crop the picture? How much does it need to be cut to fit?

**Comment by DevashishPrasad** [comment]
The script automatically resizes the image to a fixed size at the time of training as well as testing. You can find the image preprocessing pipeline in the config file. You can use image of any size, because model will be resizing it to a specific size anyhow.

**Comment by babyMonkey8** [comment]
Thank you for your reply. I have looked at the configuration file carefully and found that there are many parameters in the configuration file and I don't know what changes can be made by adjusting these parameters. Do you have any website or official document address recommendations for detailed explanation of the parameters in the configuration file?

Because I want to train from scratch, but I don't know how to label data. Do I need to label the three categories ('bordered ',' cell ',' borderless') in the picture? The tables in my picture data are quite unique. Many tables are connected together. How to mark this situation?

**Comment by DevashishPrasad** [comment]
You may have a look at this tutorial : https://www.dlology.com/blog/how-to-train-an-object-detection-model-with-mmdetection/

**Comment by babyMonkey8** [comment]
Thank you for your sharing. I read your recommendation and know the process of training my own data set. I also know that labelimg software can label image data. But when labeling, I still don't know whether I should label three types, namely 'bordered', 'cell', 'borderless'.
and the tables in my picture data are quite unique because many tables are connected together so how should I label them.

**Comment by babyMonkey8** [comment]
hello, When I started training the model with my own data, I received an error:
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.96 GiB total 
capacity; 1.22 GiB already allocated; 19.00 MiB free; 39.15 MiB cached)

**Comment by DevashishPrasad** [comment]
You are running out of your GPU memory... try reducing the batch size in config file

**Comment by babyMonkey8** [comment]
Thank you for your answer. I have another question.There are two files in the data preprocessing folder: Dilation. Py and Smudge. Py.Are these two files preprocessing the picture?Dilation and Smudge before input to model training, right?

**Comment by DevashishPrasad** [comment]
Yes, you need to use those scripts and create a new dataset having original + smudged + dilated images. And then you this dataset for training

**Comment by babyMonkey8** [comment]
Thank you for your answer. Why does this new dataset consist of three parts: original , smudged , and dilated ?If so, doesn't that amount to data enhancement?  
How do you feel about using a script and creating a new data set, the new data set: smudged , dilated？

**Comment by DevashishPrasad** [comment]
You can go through our paper in which we describe the ablation studies that show combining Dilation and Smudge augmentation techniques with the original dataset yeilds the best results
