### ISSUE TITLE
Hi all,

### ISSUE THREAD

**Issue by ranyaphat29** [DevashishPrasad/CascadeTabNet#46]
Hi all,
I'm running demo on Colab but the  Run the Predictions aren't success.

**Comment by ranyaphat29** [comment]
![Untitled](https://user-images.githubusercontent.com/22619276/83947554-e8c84100-a841-11ea-88be-1220af3f3fed.png)

My issue is above.

**Comment by DevashishPrasad** [comment]
Are you using GPU? Did you try restart rutime?

**Comment by ranyaphat29** [comment]
Thanks,sir.
