### ISSUE TITLE
Training Metrics (Precision, Recall, and F1)

### ISSUE THREAD

**Issue by rrtjr** [DevashishPrasad/CascadeTabNet#51]
Hello, thank you for the VOC to Coco script. It was very helpful. Would it be fine to ask if you used a custom script to measure model accuracy?  Are there any resources you can point where I can get more information?

**Comment by DevashishPrasad** [comment]
You can find all of the details regarding that in the **Evaluations** folder.

**Comment by rrtjr** [comment]
Ah my bad. Thanks!
