### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'

### ISSUE THREAD

**Issue by dikshantj** [DevashishPrasad/CascadeTabNet#56]
I'm trying to run the colab notebook [Model Zoo](https://colab.research.google.com/drive/1lzjbBQsF4X2C2WZhxBJz0wFEQor7F-fv?usp=sharing) but get the following error"
```
ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'
```
This issue is raised due the mmdet using the latest mmcv package which has removed this file. They are using ```mmcv>=0.6.2```

However I've fixed this by installing an older version of the mmcv in following cells as:
```
!pip install mmcv==0.4.3
```
It would be great if the colab notebook is updated so that new users do not have to face this error.

**Comment by AyanGadpal** [comment]
Hey @dikshantj 
We have updated the colab notebook 
Thank you for solving the issue
