### ISSUE TITLE
Which dataset is used for training 

### ISSUE THREAD

**Issue by shunnnosukekawai** [DevashishPrasad/CascadeTabNet#59]
I am trying to retrain for ICDAR 19 (Track B2 Modern) table structure recognition, with the latest pytorch 1.5.1 and mmdetection 2.2.1, so I would like  to know which dataset is used in this dataset link (https://drive.google.com/drive/folders/1RuEACireEqPnQrYqghEqsOPRE-CkGSUd).

And I would be happy if you could teach me how to fix the config file (cascade_mask_rcnn_hrnetv2p_w32_20e.py) for mmdetection 2.2.1.

**Comment by DevashishPrasad** [comment]
Iterative Transfer Learning (ITL) was used to train "ICDAR 19 (Track B2 Modern) table structure recognition" model. Details about ITL are mentioned in the paper.

First the model was trained on General dataset and then fine-tuned on ICDAR Table cells dataset

**Comment by kkissmart** [comment]
where did you use the tablebank?
