### ISSUE TITLE
mmdetection version and config file

### ISSUE THREAD

**Issue by trebuchet90** [DevashishPrasad/CascadeTabNet#6]
which version of mmdetection are you using and what is the config file that goes with the checkpoints?

**Comment by DevashishPrasad** [comment]
We used the newest available version of mmdetection in April 2020. After that i am not sure if they made any significant changes.

Please refer results.pdf file (https://github.com/DevashishPrasad/CascadeTabNet/blob/master/results.pdf) in which we provide link to the config files we used.

**Comment by DevashishPrasad** [comment]
The models are implemented in MMdetection Version 1.2. They have updated Mmdetection to Version 2.0, and hence the old config files are not working with the new version.

We will soon provide the old configs under the model zoo section

**Comment by trebuchet90** [comment]
it is working better now. do you have code for drawing boxes on images without matplotlib?

**Comment by DevashishPrasad** [comment]
Please refer mmdetection official documentation or this <a href="https://www.dlology.com/blog/how-to-train-an-object-detection-model-with-mmdetection/">blog</a>

**Comment by ankur7721** [comment]
@trebuchet90 Can you please tell me, which config file you used. I have used [this](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Config/cascade_mask_rcnn_hrnetv2p_w32_20e.py) and getting this error

`OSError: [WinError 145] The directory is not empty: 'C:\\Users\\pgupta5\\AppData\\Local\\Temp\\tmpizftaw7p'`

Any Idea ?
