### ISSUE TITLE
Save single file having multiple tables in an image

### ISSUE THREAD

**Issue by Atul997** [DevashishPrasad/CascadeTabNet#61]
During inference, if a image has more than one table it return two images one table at a time. How can we save a single image having multiple tables in it?

**Comment by AyogiAdityanath** [comment]
Yeah @Atul997, if you can find anything, it would help me a lot. We are working on the same sample... 👍  
Also, would help if you can solve issue with sample 4. 
Many thanks. Jai Sri Ram. 😊 🙏

**Comment by Atul997** [comment]
Where is sample?

**Comment by AyogiAdityanath** [comment]
You can find processed and clean samples [here](shorturl.at/jvyEF).  You are welcome, Jai Sri Ram 🙏

**Comment by Atul997** [comment]
url shows 404 error.

**Comment by AyogiAdityanath** [comment]
please try again, link is 100% working for me, Jai Sri Ram 🙏

**Comment by pHequals7** [comment]
> You can find processed and clean samples [here](https://shorturl.at/jvyEF). You are welcome, Jai Sri Ram 🙏

Not able to find the link :/
and pls don't use this collaborative platform to post religious remarks

**Comment by AyogiAdityanath** [comment]
okay, thank you for the constructive criticism, i will introspect, Jai Sri Ram  🙏.

**Comment by Atul997** [comment]
Please block this user.he is posting vulnerable things into the platform.

**Comment by AyogiAdityanath** [comment]
sorry @Atul997 @pHequals7 , only wanted to help, Jai Sri Ram 🙏
