### ISSUE TITLE
About colab

### ISSUE THREAD

**Issue by arnyao** [DevashishPrasad/CascadeTabNet#62]
hi 
I was wondering if the training model had to be done on Colab.
Is it ok not to use Colab?
thanks~

**Comment by DevashishPrasad** [comment]
It is perfectly fine to go without colab

**Comment by arnyao** [comment]
Thank you for answering my question.
and i have another question.when i use the checkpoint(epoch_36.pth),I want to  get an XML file for the image.
Is it true that I can only use images from ICDAR 19 dataset?
thanks~

**Comment by DevashishPrasad** [comment]
No, you can get those XML files for any given image. The format of those XML file is as per ICDAR 19 dataset
