### ISSUE TITLE
Model predictions on colored images

### ISSUE THREAD

**Issue by ankur7721** [DevashishPrasad/CascadeTabNet#63]
How is your model working on colored images, given that the dataset you have trained contains no colored image ?
Are you binarising each image before doing inference  or am i missing something ?

**Comment by DevashishPrasad** [comment]
The dataset we tried on had colored images in it.

It works well, given that the images look similar to that of colored images

**Comment by ankur7721** [comment]
Thanks @DevashishPrasad 
But my question is how is your model working on colored images, given that your training set [here ](https://drive.google.com/drive/folders/1mNDbbhu-Ubz87oRDjdtLA4BwQwwNOO-G) contains zero colored images.

**Comment by DevashishPrasad** [comment]
All of the images in the dataset are considers as RGB images no matter how they look.
