### ISSUE TITLE
XML output of extracted tabular text

### ISSUE THREAD

**Issue by sekh77** [DevashishPrasad/CascadeTabNet#8]
Hi Devashish -

For reference, is it possible to upload the XML output results of extracted tabular text for a few example documents?

Thanks,
Sekhar H.

**Comment by kshitijkapadni** [comment]
Hi, 

I have added an example of Detection of Text Chunks and it's XML in the latest commit. 

This XML is generated according to ICDAR '19 Dataset evaluation.

I'm unclear whether you are expecting the Output of OCR. If so, then I would like to clarify that we are detecting the chunks of text in the table and its bounding box, you can further use this bounding box and pass it to Tesseract OCR for the Text.

**Comment by sekh77** [comment]
Thanks for uploading the examples. I guessed it so when I saw those outputs. What I'm after is the actual text from those chunks / bounding boxes. Is it possible to add the actual text back to the same XML within the respective bounding boxes by creating a new XML tag called text? If I have to do it separately through Tesseract, then I'm not sure if I will lose the ordering of the cell contents. 
Here's my use case:

Given an image table, automatically detect the table and its structure, and then extract the text in an ordered and structured way in an XML. For example, if I have a table like this:

Header 1           Header 2             Header 3             Header 4
 1                            X                    2.5                         Y

the resulting XML should represent the output in that order (including the headers) within the respective bounding boxes.

This is what I'm not sure to achieve if I pass the bounding box coordinates separately to Tesseract.

**Comment by sekh77** [comment]
I'm still getting studying the code - so please pardon me. Does CascadeTabNet save the final image to the disk by drawing bounding boxes for the detected cells?

**Comment by kshitijkapadni** [comment]
At line no. 11 in [border.py](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Table%20Structure%20Recognition/border.py) you get all the bounding boxes of cells into a variable name final. To arrange the cells in an ordered manner you can sort the array by 1st element and then by the 2nd element of the array i.e x1 and the y1 of each bounding box. These bounding boxes can then be passed to Tesseract one by one before line no. 37 in [border.py](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Table%20Structure%20Recognition/border.py) by slicing the image such that only the ROI of the bounding box is passed to tesseract and you can add one text element in the XML element to store the output.

No, we don't save the final image with bounding boxes but you can visualize it by Uncommenting line no. 59 to 60. in [border.py](https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Table%20Structure%20Recognition/border.py) which will show the image with detected bounding boxes for the table whose coordinates have been passed to the function.
