### ISSUE TITLE
match table caption

### ISSUE THREAD

**Issue by Sunnycheey** [DevashishPrasad/CascadeTabNet#92]
Hello, first thank you for your wonderful work.

I wonder **How** can I detect the caption of the table and match it back.

May I need construct a brand new dataset contains not only table but also caption and train your model on it?

**Comment by AyanGadpal** [comment]
Hey @Sunnycheey ,
Surely that is one way you can solve it, but I would suggest using heuristics on the detected table bounding box to detect the caption (assuming that caption is present either at the top or below the table).
In the well-formatted document, the distance between caption and table will be less than other text. 
However if you are considering to generalize it across a wide variety of documents, heuristics won't give an accurate result as training the model would.
